### ISSUE TITLE
[BUG] Issue tab incorrect

### ISSUE THREAD

**Issue by adityaraute** [nhcarrigan/battlesnake-sorting-hat#12]
# Bug Report

## Describe the bug

While the Issue tab in the README file shows that 1 issue is active, the actual case (before opening this issue) is that neither an issue was open nor closed.

## Expected behavior

The Issue tab should have displayed a '0' signifying the number of open issues

## Screenshots

Had to use DOM manipulation 
![image](https://user-images.githubusercontent.com/43912470/121799628-cdf58d00-cc4a-11eb-8332-46b05d2ad7ca.png)
As can be seen no issue is open. None was closed either.

## Additional information

Might want to get rid of the tab as a whole because it doesn't provide any information that is not present on the page.

**Comment by nhcarrigan** [comment]
The issues badge is for Code Climate issues, not GitHub issues.

**Comment by adityaraute** [comment]
Don't really have an idea what that means.
